package com.jmorenov.tweetsccore.candidates;

/**
 * Candidate class that define the candidate element.
 *
 * @author <a href="mailto:jmorenov28@gmail.com">Javier Moreno</a>
 */
public class Candidate {
    private String candidate;
    private String generatedBy;

    /**
     * Constructor of the class.
     * @param candidate String with the candidate
     * @param generatedBy String with the method that generated the candidate
     */
    public Candidate(String candidate, String generatedBy) {
        this.candidate = candidate;
        this.generatedBy = generatedBy;
    }

    /**
     * Method to get the candidate.
     * @return String with the candidate
     */
    public String getCandidate() {
        return candidate;
    }

    /**
     * Method to get the method that generated the candidate.
     * @return String with the generated by
     */
    public String getGeneratedBy() {
        return generatedBy;
    }
}
